name: tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CACHE_FOLDER: ~/docker-images-${{ github.sha }}
  CACHE_FILE_SHARD: ~/docker-images-${{ github.sha }}/spqr-shard-image.tgz
  CACHE_FILE_SPQR: ~/docker-images-${{ github.sha }}/spqr-base-image.tgz
  IMAGE_SHARD: spqr-shard-image
  IMAGE_SPQR: spqr-base-image
  IMAGES_CACHE_KEY: docker-images-${{ github.sha }}

jobs:

  unit:
     name: unit
     runs-on: ubuntu-latest
     steps:

     - name: Check out code
       uses: actions/checkout@v2

     - name: unit tests
       run: make unittest

  e2e:
    name: e2e
    runs-on: ubuntu-latest
    steps:
    
    - name: Check out code
      uses: actions/checkout@v2
    
    - name: e2e tests
      run: make e2e

  stress:
    name: stress
    runs-on: ubuntu-latest
    steps:

      - name: Check out code
        uses: actions/checkout@v2

      - name: stress tests
        run: make stress
  regress:
    name: regress
    runs-on: ubuntu-latest
    steps:

      - name: Check out code
        uses: actions/checkout@v2

      - name: regress tests
        run: make regress

  feature_prepare:
    name: feature_prepare
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.step1.outputs.features }}
    steps:
      - name: Check Docker Version
        run: docker --version

      - name: Check out code
        uses: actions/checkout@v2
      - id: step1
        run: |
          make split_feature_test
          array=$(for x in $(ls test/feature/generatedFeatures); do echo $x; done | python3 -c "import sys; print(['GODOG_FEATURE_DIR=generatedFeatures GODOG_FEATURE={} make feature_test_ci'.format(test.strip()) for test in sys.stdin.readlines()])")
          echo "features=$(echo "{\"command\": $array}")" >> $GITHUB_OUTPUT
      - name: Archive production artifacts
        uses: actions/upload-artifact@v3
        with:
          name: generated_tests
          path: |
            ./test/feature/generatedFeatures


      #  use cache to pass docker images to the test jobs
      - name: Docker images caching
        id: cache-images
        uses: actions/cache@v3
        with:
          path: |
            ${{ env.CACHE_FILE_SHARD }}
            ${{ env.CACHE_FILE_SPQR }}
          key: ${{ env.IMAGES_CACHE_KEY }}

      # build images
      - name: Build images
        if: steps.cache-images.outputs.cache-hit != 'true'
        run: make save_image

  feature:
    name: feature
    runs-on: ubuntu-latest
    needs: feature_prepare
    strategy:
      matrix: ${{ fromJson(needs.feature_prepare.outputs.output1) }}
      # do not cancel all tests if one failed
      fail-fast: false
    steps:
      - name: Check Docker Version
        run: docker --version
      - name: Check out code
        uses: actions/checkout@v2
      - name: Download generatedFeatures
        uses: actions/download-artifact@v3
        with:
          name: generated_tests
          path: ./test/feature/generatedFeatures

      # load docker images
      - name: Load docker images
        id: cache-images
        uses: actions/cache@v3
        with:
          path: |
            ${{ env.CACHE_FILE_SHARD }}
            ${{ env.CACHE_FILE_SPQR }}
          key: ${{ env.IMAGES_CACHE_KEY }}

      - name: feature tests
        run: ${{ matrix.command }}
